NAPCAT_GATEWAY_NAME = "napcat"

POST_TYPE_MESSAGE = "message"
POST_TYPE_NOTICE = "notice"
POST_TYPE_META_EVENT = "meta_event"

MESSAGE_TYPE_PRIVATE = "private"
MESSAGE_TYPE_GROUP = "group"

META_EVENT_TYPE_LIFETIME = "lifecycle"
META_EVENT_TYPE_HEARTBEAT = "heartbeat"

NOTICE_TYPE_FRIEND = "friend"
NOTICE_TYPE_GROUP = "group"
NOTICE_TYPE_GROUP_MEMBER = "group_member"

SEGMENT_TYPE_TEXT = "text"
SEGMENT_TYPE_IMAGE = "image"
SEGMENT_TYPE_AT = "at"
SEGMENT_TYPE_REPLY = "reply"
SEGMENT_TYPE_FACE = "face"
SEGMENT_TYPE_VOICE = "voice"
SEGMENT_TYPE_VIDEO = "video"
SEGMENT_TYPE_RECORD = "record"
SEGMENT_TYPE_LOCATION = "location"
SEGMENT_TYPE_SHARE = "share"
SEGMENT_TYPE_GIF = "gif"
SEGMENT_TYPE_JSON = "json"
SEGMENT_TYPE_XML = "xml"
SEGMENT_TYPE_FORWARD = "forward"
SEGMENT_TYPE_POKE = "poke"
SEGMENT_TYPE_DICE = "dice"
SEGMENT_TYPE_MUSIC = "music"
SEGMENT_TYPE_RICH = "rich"

ACTION_SEND_MSG = "send_msg"
ACTION_SEND_PRIVATE_MSG = "send_private_msg"
ACTION_SEND_GROUP_MSG = "send_group_msg"
ACTION_GET_MSG = "get_msg"
ACTION_GET_STRANGER_INFO = "get_stranger_info"
ACTION_GET_FRIEND_LIST = "get_friend_list"
ACTION_GET_GROUP_LIST = "get_group_list"
ACTION_GET_GROUP_MEMBER_LIST = "get_group_member_list"
ACTION_GET_GROUP_MEMBER_INFO = "get_group_member_info"
ACTION_DELETE_MSG = "delete_msg"
ACTION_SEND_GROUP_FORWARD_MSG = "send_group_forward_msg"
ACTION_GET_LOGIN_INFO = "get_login_info"
ACTION_GET_VERSION_INFO = "get_version_info"
ACTION_SET_GROUP_KICK = "set_group_kick"
ACTION_SET_GROUP_BAN = "set_group_ban"
ACTION_SET_GROUP_WHOLE_BAN = "set_group_whole_ban"
ACTION_SET_GROUP_ADMIN = "set_group_admin"
ACTION_SET_GROUP_NAME = "set_group_name"
ACTION_SET_GROUP_LEAVE = "set_group_leave"
